name: "Frogbot Scan Repository"
on:
  workflow_dispatch:
  schedule:
    # The repository will be scanned once a day at 00:00 GMT.
    - cron: "0 0 * * *"
  push:
    branches:
      - main
permissions:
  pull-requests: write
  contents: write
  security-events: write
  id-token: write

jobs:
  scan-repository:
    runs-on: ubuntu-latest
    name: Scan Repository (${{ matrix.branch }} branch)
    strategy:
      matrix:
        branch: [ "main" ]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # - name: Setup Java
      #   uses: actions/setup-java@v4
      #   with:
      #     java-version: '21'
      #     distribution: 'temurin'
      - uses: jfrog/frogbot@v2
        env:
          JF_URL: ${{ vars.JF_URL }}
          JF_GIT_TOKEN: ${{ vars.JF_GIT_TOKEN }}
          JF_GIT_BASE_BRANCH: ${{ matrix.branch }}
        with:
          oidc-provider-name: jonw-apac/spring-petclinic@github